# Fina CLI Configuration File
# ---------------------------
# This is an example configuration file for the Fina CLI.
# You can place this file at ~/.fina/config.yml (Linux/macOS)
# or ~/.finarc in your home directory.
# The full list of locations respected are:
# 1. -C or --config argument provided to command (relative path)
# 2. "fina" property in package.json in current directory.
# 3. ~/.finarc
# 4. ~/.fina/config
# 5. ~/.fina/config.json
# 6. ~/.fina/config.yaml
# 7. ~/.fina/config.yml
# 8. ~/.fina/config.js

# --- Defaults ---
# Set the default provider and output format to be used when no command-line
# flags are specified. This is great for setting your personal preference.
defaults:
  provider: "alphavantage"
  output: "csv"

# --- Providers ---
# This is where you configure your API keys and provider-specific settings.
# API keys here can be overridden by environment variables (e.g., ALPHAVANTAGE_API_KEY).
providers:
  alphavantage:
    # Your Alpha Vantage API key is required to fetch data.
    apiKey: "YOUR_ALPHAVANTAGE_API_KEY_HERE"

    # The number of API calls allowed per minute.
    # The free tier is 5. Premium tiers are much higher (e.g., 4500 for 75/sec).
    rateLimitPerMinute: 5

  polygon:
    # Example configuration for a future Polygon.io provider.
    apiKey: "YOUR_POLYGON_API_KEY_HERE"

# --- Cache & Database ---
# Customize the location and type of your local cache.

# The full path to the SQLite database file for your cache.
# If commented out, defaults to ~/.fina/cache.sqlite
databasePath: "~/Documents/FinancialData/fina_cache.sqlite"

# Specifies the type of cache to use. (Currently only sqlite is implemented).
# Other future options could include 'flatfile' or 'in-memory'.
cache:
  type: "sqlite"

# Spefiies log level, defaults to info.
# Available options are DEBUG, INFO, WARN, ERROR.
logLevel: INFO
